# -*- coding: utf-8 -*-
"""nano_gpt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rY0AhzeuY-_oCeXlAMmy_GEzzMGThC5
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1337)
import matplotlib.pyplot as plt
# %matplotlib inline

data = open('input.txt', 'r').read()
print(data[:1000])

chars = sorted(list(set(data)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

# mapping between char and integer for each unique character
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # output list of all integers
decode = lambda a: ''.join([itos[i] for i in a]) # output string
print(encode("hii there!"))
print(decode(encode("hii there!")))

n = int(0.9*len(data))
train_data = encode(data[:n])
val_data = encode(data[n:])

torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
  data = train_data if split == 'train' else val_data
  data = torch.tensor(data, dtype=torch.long) # Convert data to a torch.LongTensor here
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')


class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, idx, targets=None):
    logits = self.token_embedding_table(idx) # (B,T,C)

    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def genereate(self, idx, max_new_tokens):

    for _ in range(max_new_tokens):

      logits, loss = self(idx)
      logits = logits[:, -1, :]
      softmax = F.softmax(logits, dim=-1)
      idx_next = torch.multinomial(softmax, num_samples=1)
      idx = torch.cat((idx, idx_next), dim=1)
    return idx

m = BigramLanguageModel(vocab_size)
out, loss = m(xb, yb)
print(out.shape)
print(loss)

idx = torch.zeros((1,1), dtype=torch.long)
print(decode(m.genereate(idx, max_new_tokens=100)[0].tolist()))

optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

batch_size = 32
for steps in range(20000):
  # get sample batch from training set
  xb, yb = get_batch('train')

  # evaluate loss and optimize
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

  if steps % 1000 == 0:
    print(loss.item())

print(decode(m.genereate(idx, max_new_tokens=500)[0].tolist()))